language: c
compiler: gcc
addons:
  apt:
    packages:
    - gcc-arm-linux-gnueabihf
script: ARCH=arm make bb.org_defconfig && make -j4 CROSS_COMPILE=arm-linux-gnueabihf- && make KBUILD_DEBARCH=armhf KDEB_SOURCENAME=linux KDEB_CHANGELOG_DIST=unstable LOCALVERSION=-git$TRAVIS_COMMIT
